db:
  image: tenforce/virtuoso
  restart: always
  environment:
    SPARQL_UPDATE: "true"
    DEFAULT_GRAPH: "http://publications.europa.eu/resource"
    DBA_PASSWORD: "amarkc0023"
  volumes:
    - ~/virtuoso/virtuoso_data:/data
  ports:
    - "8890:8890"
    - "1111:1111"
